.TH nimf 1 "7 Jun 2019"
.SH NAME
nimf \- Nimf input method daemon
.SH SYNOPSIS
.B nimf
[OPTIONS]
.SH DESCRIPTION
nimf is an input method daemon.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show help messages
.TP
.B \-\-debug
Log debugging messages
.TP
.B \-\-version
Show version
.SH "EXIT STATUS"
It returns 0 on success, non-zero on failure.
.SH "SEE ALSO"
.BR nimf-settings (1)
